---
# Configure a common baseline for all hosts
- hosts: vagrant
  become: true
  roles:
    - role: OULibraries.centos7
      tags: centos7
  pre_tasks:
    - include: pretasks.yml
      tags: pretasks

# Nothing specifically gets configured in this generic host. If it
# did, that would go here.
#
# - hosts: dev.vagrant.localdomain
#   sudo: yes
#   roles:
#     - role: OULibraries.role
#       tags: role

# Got back and configure interactive users and devel settings for all hosts
- hosts: vagrant
  become: true
  roles:
    - role: OULibraries.users
      tags: users
