---
# Style of environment to build: vagrant, test or prod
environment_name: "vagrant"

# Local credentials
# additional shell accounts
users:
  - name: 'libacct'
    groups: 'wheel'
    pubkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAtkaGGkonm3HJmRoupKgM0A04uZu3aPhFyWmyMWCHTk1TtDskTgO0krOgUKuxAB2G/d39Xz6oISL9+dQdZt5aEJK7WoHpkK8l8xXfrIJ8OiWuJ+IRygjjLsib8tVTRsEIvMrQUtnhGzVNM7lQNXaEviGmR+ZunH68fv/QpomR5qW/veLFsR0KQLnd8yoG2+Tm8EdYouDcUPTS1nr9XdPSWGcsvpDq48JdxSmtXXC/8NHfdhpmCMmoC/IXbFl7typeLd9gt7EFvqOLWEbysEF3hD6hMAV3MEWaDnhf25n2cUgdAvdk086REgg2bXx1dBdeSi+wq5MadfP80UuPuaN2lw== libacct@ou.edu'

ssh_brokers:
  - alias: 'localhost'
    ip: '127.0.0.1'
    dn_suffix: 'localdomain'

# root db password
mariadb_root_pass: 'root'

# Passing the local domain on to apache
httpd_dn_suffix: "vagrant.dev"

# Local APC credentials
apc_username: apcuser
apc_password: apcpass

# Front end
# nginx_star_sites: [] # Use this if you have no star sites
nginx_star_sites:
 - name: cas.vagrant.dev
   upstreams:
     - name: cas-vagrant-dev
       servers:
         - cas.vagrant.dev:443
   robots: disallow
# nginx_literal_sites: [] # Use this if you have no literal sites
nginx_literal_sites:[]
