users:
  - name: 'libacct'
    groups: 'wheel,apache'
    pubkey: '{{ libacct_pubkey }}'
  - name: '{{my_user}}'
    groups: 'wheel,apache'
    pubkey: '{{ my_pubkey }}'

users_secure_path: '/sbin:/bin:/usr/sbin:/usr/bin:/opt/php/bin'    
